import type { ChatTurn, GenerateOptions, LlamaEngine } from './LlamaEngine';

export class FakeLlamaEngine implements LlamaEngine {
  private stopped = false;

  async loadModel(): Promise<void> {
    await new Promise<void>(resolve => setTimeout(resolve, 300));
  }

  async generate(
    messages: ChatTurn[],
    onToken: (token: string) => void,
    _options?: GenerateOptions,
  ): Promise<void> {
    this.stopped = false;

    const prompt =
      [...messages].reverse().find(message => message.role === 'user')
        ?.content ?? '';

    const response =
      `You said: "${prompt}"\n\n` +
      'This response is currently generated by the fake engine. ' +
      'Soon this exact interface will call llama.cpp locally.';

    const tokens = response.split(/(\s+)/);

    for (const token of tokens) {
      if (this.stopped) {
        return;
      }

      onToken(token);

      await new Promise<void>(resolve => setTimeout(resolve, 35));
    }
  }

  async stopGeneration(): Promise<void> {
    this.stopped = true;
  }
}
